branches:
  only:
  - master
services: 
- docker
push: &push
      addons:
        apt:
          packages:
            - docker-ce
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - |
          for i in `docker images --format {{.Repository}}:{{.Tag}}`; do
            if [[ $TRAVIS_EVENT_TYPE == "push" ]]; then 
              docker push $i;
            fi
          done
alpine: &alpine
      stage: Build
      os: linux
      language: shell
      script:
        - docker version
        - docker-compose -f dist/alpine/docker-compose.yml build
        - docker rmi golang:alpine3.11
        - docker rmi raphaelguzman/miniconda3:${CONDA_VER}-py${PY_VER}-alpine3.11
        - docker system prune -f
      <<: *push
debian: &debian
      stage: Build
      os: linux
      language: shell
      script:
        - docker version
        - docker-compose -f dist/debian/docker-compose.yml build
        - docker rmi golang:alpine3.11
        - docker rmi raphaelguzman/miniconda3:${CONDA_VER}-py${PY_VER}-debian
        - docker system prune -f
      <<: *push
jobs:
  include:
    - <<: *alpine
      env:
      - LABEL: Alpine
      - PY_VER: 3.8
      - CONDA_VER: 4.8.2
    - <<: *alpine
      env:
      - LABEL: Alpine
      - PY_VER: 3.7
      - CONDA_VER: 4.8.2
    - <<: *alpine
      env:
      - LABEL: Alpine
      - PY_VER: 3.6
      - CONDA_VER: 4.4.10
    - <<: *debian
      env:
      - LABEL: Debian
      - PY_VER: 3.8
      - CONDA_VER: 4.8.2
    - <<: *debian
      env:
      - LABEL: Debian
      - PY_VER: 3.7
      - CONDA_VER: 4.8.2
    - <<: *debian
      env:
      - LABEL: Debian
      - PY_VER: 3.6
      - CONDA_VER: 4.4.10
